all: hello switchcase whileloop

hello: hello.cpp
switchcase: switchcase.cpp
#forloop: forloop.cpp
whileloop: whileloop.cpp
externallib: externallib.cpp -I/opt/ros/kinetic/include/ -rdynamic /opt/ros/kinetic/lib/
